[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 300

[env]
title = "Alacritty"

[font]
size = 14

[font.bold]
family = "JetBrains Mono"
style = "Regular"

[font.glyph_offset]
x = 1
y = 1

[font.italic]
family = "JetBrains Mono"
style = "Thin Italic"

[font.normal]
family = "JetBrains Mono"
style = "Light"

[font.offset]
x = 1
y = 2

[scrolling]
history = 5000
multiplier = 3

[window]
dynamic_title = true
opacity = 0.99

[window.padding]
x = 2
y = 2

[colors.primary]
background = '#f8f8f8'
foreground = '#2a2b33'

[colors.normal]
black   = '#000000'
red     = '#de3d35'
green   = '#3e953a'
yellow  = '#d2b67b'
blue    = '#2f5af3'
magenta = '#a00095'
cyan    = '#3e953a'
white   = '#bbbbbb'

[colors.bright]
black   = '#000000'
red     = '#de3d35'
green   = '#3e953a'
yellow  = '#d2b67b'
blue    = '#2f5af3'
magenta = '#a00095'
cyan    = '#3e953a'
white   = '#ffffff'
