[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 300

[env]
title = "Alacritty"

[font]
size = 13

[font.bold]
family = "FiraCode Nerd Font"
style = "Medium"

[font.glyph_offset]
x = 1
y = 2

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 4

[scrolling]
history = 5000
multiplier = 3

[window]
dynamic_title = true
opacity = 0.99

[window.padding]
x = 4
y = 6

[colors.primary]
background = '#f8f8f8'
foreground = '#2a2b33'

[colors.normal]
black   = '#000000'
red     = '#de3d35'
green   = '#3e953a'
yellow  = '#d2b67b'
blue    = '#2f5af3'
magenta = '#a00095'
cyan    = '#3e953a'
white   = '#bbbbbb'

[colors.bright]
black   = '#000000'
red     = '#de3d35'
green   = '#3e953a'
yellow  = '#d2b67b'
blue    = '#2f5af3'
magenta = '#a00095'
cyan    = '#3e953a'
white   = '#ffffff'
